/* eslint-disable @next/next/no-img-element */
"use client";

import { useUI } from "../context";

export default function Foundations() {
  const ui = useUI();
  return (
    <section id="fnd" data-spy="fnd" data-screen-label="01 Foundations" style={{ padding: "64px 0 30px", borderTop: "1px solid var(--bd2)" }}>
      <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: "16px", flexWrap: "wrap" }}>
        <div>
          <div style={{ fontFamily: "'Space Mono',monospace", fontSize: "12px", letterSpacing: ".2em", textTransform: "uppercase", color: "var(--accent)" }}><span style={{ opacity: ".5" }}>[</span>&nbsp; 01 — Foundations &nbsp;<span style={{ opacity: ".5" }}>]</span></div>
          <h2 style={{ fontFamily: "'Space Grotesk',sans-serif", fontWeight: 600, fontSize: "clamp(1.7rem,3vw,2.4rem)", lineHeight: "1.08", letterSpacing: "-.025em", margin: "14px 0 0", color: "var(--ink)" }}>Brand, color &amp; texture.</h2>
        </div>
        <span style={{ fontFamily: "'Space Mono',monospace", fontSize: "11.5px", letterSpacing: ".12em", color: "var(--faint)" }}>04 items</span>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(300px,1fr))", gap: "18px", marginTop: "34px" }}>
        <div style={{ border: "1px solid var(--bd)", borderRadius: "16px", background: "var(--surface)", overflow: "hidden" }}>
          <div style={{ display: "flex", justifyContent: "space-between", gap: "10px", padding: "12px 18px", borderBottom: "1px solid var(--bd2)", fontFamily: "'Space Mono',monospace", fontSize: "11px", letterSpacing: ".14em", textTransform: "uppercase", color: "var(--faint)" }}><span>F-01 · Wordmark</span><span>3 colorways</span></div>
          <div style={{ padding: "22px", display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(104px,1fr))", gap: "10px" }}>
            <div style={{ border: "1px solid #E4DECF", background: "#F5F2EA", borderRadius: "12px", padding: "20px 14px 14px", display: "flex", flexDirection: "column", alignItems: "center", gap: "12px" }}><img src="/assets/logo-dark.png" alt="D-ALabs wordmark on paper" style={{ width: "100%", maxWidth: "130px", height: "auto" }} /><span style={{ fontFamily: "'Space Mono',monospace", fontSize: "9.5px", letterSpacing: ".16em", textTransform: "uppercase", color: "#8A93A0" }}>Lab</span></div>
            <div style={{ background: "#0D1522", borderRadius: "12px", padding: "20px 14px 14px", display: "flex", flexDirection: "column", alignItems: "center", gap: "12px" }}><img src="/assets/logo-dark.png" alt="D-ALabs wordmark inverted on dark" style={{ width: "100%", maxWidth: "130px", height: "auto", filter: "invert(1)" }} /><span style={{ fontFamily: "'Space Mono',monospace", fontSize: "9.5px", letterSpacing: ".16em", textTransform: "uppercase", color: "#6C7A8C" }}>Dark</span></div>
            <div style={{ background: "#081426", borderRadius: "12px", padding: "20px 14px 14px", display: "flex", flexDirection: "column", alignItems: "center", gap: "12px" }}><img src="/assets/logo-light.png" alt="D-ALabs wordmark gold on abyss" style={{ width: "100%", maxWidth: "130px", height: "auto" }} /><span style={{ fontFamily: "'Space Mono',monospace", fontSize: "9.5px", letterSpacing: ".16em", textTransform: "uppercase", color: "#6E8198" }}>Ark</span></div>
          </div>
        </div>
        <div style={{ border: "1px solid var(--bd)", borderRadius: "16px", background: "var(--surface)", overflow: "hidden" }}>
          <div style={{ display: "flex", justifyContent: "space-between", gap: "10px", padding: "12px 18px", borderBottom: "1px solid var(--bd2)", fontFamily: "'Space Mono',monospace", fontSize: "11px", letterSpacing: ".14em", textTransform: "uppercase", color: "var(--faint)" }}><span>F-02 · Flask mark</span><span>Signature</span></div>
          <div style={{ padding: "22px", display: "flex", alignItems: "center", justifyContent: "center", gap: "26px" }}>
            <span style={{ display: "grid", placeItems: "center", padding: "16px 20px", borderRadius: "12px", background: "var(--orbit-bg)", transition: "background-color .45s ease" }}><img src="/assets/flask.png" alt="Flask mark" style={{ height: "84px", width: "auto", display: "var(--show-fn)", filter: "var(--flask-fx) drop-shadow(0 14px 22px rgba(22,32,46,.22))" }} /><img src="/assets/flask-gold.png" alt="Flask mark" style={{ height: "84px", width: "auto", display: "var(--show-fg)", filter: "drop-shadow(0 14px 22px rgba(0,0,0,.35))" }} /></span>
            <div style={{ fontFamily: "'Space Mono',monospace", fontSize: "11.5px", letterSpacing: ".1em", lineHeight: "2.1", color: "var(--faint)", textTransform: "uppercase" }}>Clear-space ½×<br />Min height 20px<br />Never recolored</div>
          </div>
        </div>
      </div>

      <div style={{ border: "1px solid var(--bd)", borderRadius: "16px", background: "var(--surface)", overflow: "hidden", marginTop: "18px" }}>
        <div style={{ display: "flex", justifyContent: "space-between", gap: "10px", padding: "12px 18px", borderBottom: "1px solid var(--bd2)", fontFamily: "'Space Mono',monospace", fontSize: "11px", letterSpacing: ".14em", textTransform: "uppercase", color: "var(--faint)" }}><span>F-03 · Palette — click to copy</span><span>Lab / Ark</span></div>
        <div style={{ padding: "22px" }}>
          <div style={{ fontFamily: "'Space Mono',monospace", fontSize: "10.5px", letterSpacing: ".16em", textTransform: "uppercase", color: "var(--faint)", marginBottom: "12px" }}>Lab — paper &amp; ink</div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(118px,1fr))", gap: "10px" }}>
            <button onClick={ui.copyHex} data-hex="#F5F2EA" style={{ textAlign: "left", cursor: "pointer", border: "1px solid var(--bd)", borderRadius: "12px", background: "var(--surface)", padding: "8px", transition: "border-color .25s" }} className="hov-bd"><span style={{ display: "block", height: "52px", borderRadius: "8px", background: "#F5F2EA", border: "1px solid #E4DECF" }}></span><span style={{ display: "block", marginTop: "8px", fontSize: "12.5px", fontWeight: 600, color: "var(--ink)" }}>Paper</span><span style={{ display: "block", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", color: "var(--faint)" }}>#F5F2EA</span></button>
            <button onClick={ui.copyHex} data-hex="#FCFBF7" style={{ textAlign: "left", cursor: "pointer", border: "1px solid var(--bd)", borderRadius: "12px", background: "var(--surface)", padding: "8px", transition: "border-color .25s" }} className="hov-bd"><span style={{ display: "block", height: "52px", borderRadius: "8px", background: "#FCFBF7", border: "1px solid #E4DECF" }}></span><span style={{ display: "block", marginTop: "8px", fontSize: "12.5px", fontWeight: 600, color: "var(--ink)" }}>Card</span><span style={{ display: "block", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", color: "var(--faint)" }}>#FCFBF7</span></button>
            <button onClick={ui.copyHex} data-hex="#E4DECF" style={{ textAlign: "left", cursor: "pointer", border: "1px solid var(--bd)", borderRadius: "12px", background: "var(--surface)", padding: "8px", transition: "border-color .25s" }} className="hov-bd"><span style={{ display: "block", height: "52px", borderRadius: "8px", background: "#E4DECF" }}></span><span style={{ display: "block", marginTop: "8px", fontSize: "12.5px", fontWeight: 600, color: "var(--ink)" }}>Sand line</span><span style={{ display: "block", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", color: "var(--faint)" }}>#E4DECF</span></button>
            <button onClick={ui.copyHex} data-hex="#8A93A0" style={{ textAlign: "left", cursor: "pointer", border: "1px solid var(--bd)", borderRadius: "12px", background: "var(--surface)", padding: "8px", transition: "border-color .25s" }} className="hov-bd"><span style={{ display: "block", height: "52px", borderRadius: "8px", background: "#8A93A0" }}></span><span style={{ display: "block", marginTop: "8px", fontSize: "12.5px", fontWeight: 600, color: "var(--ink)" }}>Mist</span><span style={{ display: "block", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", color: "var(--faint)" }}>#8A93A0</span></button>
            <button onClick={ui.copyHex} data-hex="#54606E" style={{ textAlign: "left", cursor: "pointer", border: "1px solid var(--bd)", borderRadius: "12px", background: "var(--surface)", padding: "8px", transition: "border-color .25s" }} className="hov-bd"><span style={{ display: "block", height: "52px", borderRadius: "8px", background: "#54606E" }}></span><span style={{ display: "block", marginTop: "8px", fontSize: "12.5px", fontWeight: 600, color: "var(--ink)" }}>Slate</span><span style={{ display: "block", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", color: "var(--faint)" }}>#54606E</span></button>
            <button onClick={ui.copyHex} data-hex="#16202E" style={{ textAlign: "left", cursor: "pointer", border: "1px solid var(--bd)", borderRadius: "12px", background: "var(--surface)", padding: "8px", transition: "border-color .25s" }} className="hov-bd"><span style={{ display: "block", height: "52px", borderRadius: "8px", background: "#16202E" }}></span><span style={{ display: "block", marginTop: "8px", fontSize: "12.5px", fontWeight: 600, color: "var(--ink)" }}>Ink</span><span style={{ display: "block", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", color: "var(--faint)" }}>#16202E</span></button>
            <button onClick={ui.copyHex} data-hex="#0E1620" style={{ textAlign: "left", cursor: "pointer", border: "1px solid var(--bd)", borderRadius: "12px", background: "var(--surface)", padding: "8px", transition: "border-color .25s" }} className="hov-bd"><span style={{ display: "block", height: "52px", borderRadius: "8px", background: "#0E1620" }}></span><span style={{ display: "block", marginTop: "8px", fontSize: "12.5px", fontWeight: 600, color: "var(--ink)" }}>Footer ink</span><span style={{ display: "block", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", color: "var(--faint)" }}>#0E1620</span></button>
          </div>
          <div style={{ fontFamily: "'Space Mono',monospace", fontSize: "10.5px", letterSpacing: ".16em", textTransform: "uppercase", color: "var(--faint)", margin: "24px 0 12px" }}>Ark — abyss &amp; gold</div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(118px,1fr))", gap: "10px" }}>
            <button onClick={ui.copyHex} data-hex="#081426" style={{ textAlign: "left", cursor: "pointer", border: "1px solid var(--bd)", borderRadius: "12px", background: "var(--surface)", padding: "8px", transition: "border-color .25s" }} className="hov-bd"><span style={{ display: "block", height: "52px", borderRadius: "8px", background: "#081426" }}></span><span style={{ display: "block", marginTop: "8px", fontSize: "12.5px", fontWeight: 600, color: "var(--ink)" }}>Abyss</span><span style={{ display: "block", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", color: "var(--faint)" }}>#081426</span></button>
            <button onClick={ui.copyHex} data-hex="#0E1D34" style={{ textAlign: "left", cursor: "pointer", border: "1px solid var(--bd)", borderRadius: "12px", background: "var(--surface)", padding: "8px", transition: "border-color .25s" }} className="hov-bd"><span style={{ display: "block", height: "52px", borderRadius: "8px", background: "#0E1D34" }}></span><span style={{ display: "block", marginTop: "8px", fontSize: "12.5px", fontWeight: 600, color: "var(--ink)" }}>Hull</span><span style={{ display: "block", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", color: "var(--faint)" }}>#0E1D34</span></button>
            <button onClick={ui.copyHex} data-hex="#050E1D" style={{ textAlign: "left", cursor: "pointer", border: "1px solid var(--bd)", borderRadius: "12px", background: "var(--surface)", padding: "8px", transition: "border-color .25s" }} className="hov-bd"><span style={{ display: "block", height: "52px", borderRadius: "8px", background: "#050E1D" }}></span><span style={{ display: "block", marginTop: "8px", fontSize: "12.5px", fontWeight: 600, color: "var(--ink)" }}>Depth</span><span style={{ display: "block", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", color: "var(--faint)" }}>#050E1D</span></button>
            <button onClick={ui.copyHex} data-hex="#D9AE63" style={{ textAlign: "left", cursor: "pointer", border: "1px solid var(--bd)", borderRadius: "12px", background: "var(--surface)", padding: "8px", transition: "border-color .25s" }} className="hov-bd"><span style={{ display: "block", height: "52px", borderRadius: "8px", background: "#D9AE63" }}></span><span style={{ display: "block", marginTop: "8px", fontSize: "12.5px", fontWeight: 600, color: "var(--ink)" }}>Gold</span><span style={{ display: "block", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", color: "var(--faint)" }}>#D9AE63</span></button>
            <button onClick={ui.copyHex} data-hex="#E8C074" style={{ textAlign: "left", cursor: "pointer", border: "1px solid var(--bd)", borderRadius: "12px", background: "var(--surface)", padding: "8px", transition: "border-color .25s" }} className="hov-bd"><span style={{ display: "block", height: "52px", borderRadius: "8px", background: "#E8C074" }}></span><span style={{ display: "block", marginTop: "8px", fontSize: "12.5px", fontWeight: 600, color: "var(--ink)" }}>Brass</span><span style={{ display: "block", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", color: "var(--faint)" }}>#E8C074</span></button>
            <button onClick={ui.copyHex} data-hex="#F2ECDD" style={{ textAlign: "left", cursor: "pointer", border: "1px solid var(--bd)", borderRadius: "12px", background: "var(--surface)", padding: "8px", transition: "border-color .25s" }} className="hov-bd"><span style={{ display: "block", height: "52px", borderRadius: "8px", background: "#F2ECDD", border: "1px solid #E4DECF" }}></span><span style={{ display: "block", marginTop: "8px", fontSize: "12.5px", fontWeight: 600, color: "var(--ink)" }}>Ivory</span><span style={{ display: "block", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", color: "var(--faint)" }}>#F2ECDD</span></button>
            <button onClick={ui.copyHex} data-hex="#9FB1C6" style={{ textAlign: "left", cursor: "pointer", border: "1px solid var(--bd)", borderRadius: "12px", background: "var(--surface)", padding: "8px", transition: "border-color .25s" }} className="hov-bd"><span style={{ display: "block", height: "52px", borderRadius: "8px", background: "#9FB1C6" }}></span><span style={{ display: "block", marginTop: "8px", fontSize: "12.5px", fontWeight: 600, color: "var(--ink)" }}>Harbor</span><span style={{ display: "block", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", color: "var(--faint)" }}>#9FB1C6</span></button>
          </div>
        </div>
      </div>

      <div style={{ border: "1px solid var(--bd)", borderRadius: "16px", background: "var(--surface)", overflow: "hidden", marginTop: "18px" }}>
        <div style={{ display: "flex", justifyContent: "space-between", gap: "10px", padding: "12px 18px", borderBottom: "1px solid var(--bd2)", fontFamily: "'Space Mono',monospace", fontSize: "11px", letterSpacing: ".14em", textTransform: "uppercase", color: "var(--faint)" }}><span>F-04 · Texture</span><span>Backgrounds</span></div>
        <div style={{ padding: "22px", display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(200px,1fr))", gap: "12px" }}>
          <div style={{ position: "relative", height: "130px", borderRadius: "12px", border: "1px solid var(--bd)", overflow: "hidden", background: "var(--bg)" }}>
            <div style={{ position: "absolute", inset: "0", backgroundImage: "linear-gradient(var(--grid) 1px,transparent 1px),linear-gradient(90deg,var(--grid) 1px,transparent 1px)", backgroundSize: "32px 32px" }}></div>
            <span style={{ position: "absolute", left: "12px", bottom: "10px", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", letterSpacing: ".12em", textTransform: "uppercase", color: "var(--faint)" }}>Blueprint grid · 46px</span>
          </div>
          <div style={{ position: "relative", height: "130px", borderRadius: "12px", border: "1px solid var(--bd)", overflow: "hidden", background: "var(--bg)" }}>
            <div style={{ position: "absolute", inset: "0", opacity: ".5", backgroundImage: "url('data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22140%22 height=%22140%22%3E%3Cfilter id=%22n%22%3E%3CfeTurbulence type=%22fractalNoise%22 baseFrequency=%220.85%22 numOctaves=%222%22 stitchTiles=%22stitch%22/%3E%3C/filter%3E%3Crect width=%22100%25%22 height=%22100%25%22 filter=%22url(%23n)%22/%3E%3C/svg%3E')" }}></div>
            <span style={{ position: "absolute", left: "12px", bottom: "10px", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", letterSpacing: ".12em", textTransform: "uppercase", color: "var(--ink)" }}>Film grain · 4–5%</span>
          </div>
          <div style={{ position: "relative", height: "130px", borderRadius: "12px", border: "1px solid var(--bd)", overflow: "hidden", background: "var(--bg)" }}>
            <div data-loop="" style={{ position: "absolute", inset: "-30%", background: "radial-gradient(circle at 50% 55%, var(--accent-soft), transparent 60%)", animation: "glowPulse 5.5s ease-in-out infinite" }}></div>
            <span style={{ position: "absolute", left: "12px", bottom: "10px", fontFamily: "'Space Mono',monospace", fontSize: "10.5px", letterSpacing: ".12em", textTransform: "uppercase", color: "var(--faint)" }}>Radial glow · accent 8–16%</span>
          </div>
        </div>
      </div>
    </section>
  );
}
